import {
    Code,
    FileCode,
    Atom,
    Database,
    Server,
    Settings,
    GitBranch,
    Docker,
    Globe,
    Shield,
    Pencil,
    BookOpen,
    Terminal,
    Layout,
    Braces,
    ClipboardList,
    Languages,
    Figma,
    PenTool,
    Markdown,
    Html,
    Css,
    Java,
    Python,
    Php,
    Go,
    Bash,
    GitHub,
    Git,
    Vercel,
    XCircle,
} from "lucide-react";

export const skillIcons = {
    C: Code,
    "C++": Code,
    Java: Java,
    JavaScript: FileCode,
    Typescript: FileCode,
    Python: Python,
    PHP: Php,
    Go: Go,
    "Bash script": Bash,
    HTML5: Html,
    CSS3: Css,
    TailwindCSS: Layout,
    React: Atom,
    NodeJS: Server,
    ExpressJS: Server,
    Firebase: Database,
    MySQL: Database,
    MongoDB: Database,
    Docker: Docker,
    Git: Git,
    GitHub: GitHub,
    Vercel: Vercel,
    XAMPP: Server,
    Algorithm: Braces,
    "Data Structure": Braces,
    OOP: ClipboardList,
    "System Design": Settings,
    "Ethical Hacking": Shield,
    LaTeX: BookOpen,
    Figma: Figma,
    Canva: PenTool,
    Markdown: Markdown,
};
